<?php

namespace Jariff\SuperAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompetitorStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitorStatusRepository extends EntityRepository
{
}
