<?php

namespace Jariff\SuperAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DailyRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyRankRepository extends EntityRepository
{
	public function findByCompetitorOrderByDate($id, $beginning, $end){
		$query = $this->getEntityManager()->createQuery('
			SELECT d
			FROM JariffAdminBundle:DailyRank d WHERE d.competitor=:id  ORDER BY d.id DESC
			');
			$query->setParameter('id', $id);
		if ($beginning != '' && $end != '') {
			$query = $this->getEntityManager()->createQuery('
				SELECT d
				FROM JariffAdminBundle:DailyRank d
				WHERE d.competitor=:id AND d.date > :beginning AND d.date < :end
				');
			$query->setParameter('id', $id);
			$query->setParameter('beginning', \DateTime::createFromFormat('Y-m-d', $beginning));
			$query->setParameter('end', \DateTime::createFromFormat('Y-m-d', $end));
		} else {
			$query->setMaxResults(30);
		}
		$result = $query->getResult();
		return $result;
	}
}
