<?php

namespace Jariff\SuperAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeadContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadContactRepository extends EntityRepository
{
}
