<?php

namespace Jariff\SuperAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperAdminRepository extends EntityRepository
{
}
