imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@JariffProjectBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

#enable intl extensions
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ JariffProjectBundle, JariffAdminBundle, JariffMemberBundle, JariffSuperAdminBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: JariffProjectBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: JariffProjectBundle:Menu:knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

# knp_snappy:
#    pdf:
#        enabled:    true
#        binary:     "xvfb-run -a -s \"-screen 0 640x480x16\" -e %kernel.root_dir%/logs/snappy.log /usr/bin/wkhtmltopdf"
#        options:    []
#    image:
#        enabled:    true
#        binary:     "xvfb-run -a -s \"-screen 0 640x480x16\" -e %kernel.root_dir%/logs/snappy.log /usr/bin/wkhtmltoimage"
#        options:    []

knp_snappy:
   pdf:
       enabled:    true
       binary:     "xvfb-run -a -s \"-screen 0 640x480x16\" -e %kernel.root_dir%/logs/snappy.log /usr/bin/wkhtmltopdf"
       options:    []
   image:
       enabled:    true
       binary:     "xvfb-run -a -s \"-screen 0 640x480x16\" -e %kernel.root_dir%/logs/snappy.log /usr/bin/wkhtmltoimage"
       options:    []

jariff_authorize_net:
    api_login_id: 72A5rTkK
    api_transaction_key: 7H65g3MS3x7ge2Pd
    sandbox: true

jariff_admin:
    echosign_url: https://secure.echosign.com/services/EchoSignDocumentService16?wsdl
    echosign_api_key: XXTYLPI3J3Z6B64

# apy_data_grid:
#     persistence: true