<?php

namespace Jariff\MemberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberChildRepository extends EntityRepository
{
}
