<?php

namespace Jariff\MemberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberSubscriptionActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberSubscriptionActivityRepository extends EntityRepository
{
}
