<?php

namespace Jariff\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EarningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EarningRepository extends EntityRepository
{
	public function findByJoinDayDate($today){
		$query = $this->getEntityManager()->createQuery('
			SELECT d
			FROM JariffAdminBundle:Admin d WHERE d.joinDate=:joinDate  ORDER BY d.id DESC
			');
		$query->setParameter('joinDate', $today);
		
		$result = $query->getResult();
		return $result;
	}
}
