<?php

namespace Jariff\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeadDataInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadDataInterestRepository extends EntityRepository
{
}
